dist: trusty
language: c
compiler: gcc

# build all branches
branches:
  only:
  - /.*/

stages:
  - build
#  - test

before_install:
# needed for compiling 32bit software on 64bit machine
  - sudo apt-get install gcc-multilib
  
jobs:
  include:
    - stage: build
      name: "BuildSimpleExample"
      script:
        -cmake ./ci/simple_app
        -make -C ./cfs
    - stage: build
      name: "BuildSGP4Example"
      script: cmake ./ci/sgp4
        -cmake ./ci/sgp4
        -make -C ./cfs
    
#before_script:
    
#notifications:
#  email:
#    recipients:
#      - steven.lentine@nasa.gov
#    on_success: change
#    on_failure: always
